[package]
name = "shaderc-sys"
version = "0.4.1"
authors = ["Lei Zhang <antiagainst@gmail.com>", "Mr. Knapp <knappador@gmail.com>"]
build = "build/build.rs"
description = "Raw bindings for shaderc"
repository = "https://github.com/google/shaderc-rs"
documentation = "https://docs.rs/shaderc"
readme = "README.md"
license = "Apache-2.0"
keywords = ["shader", "compiler", "spirv", "glsl", "hlsl"]
links = "shaderc"

[lib]
name = "shaderc_sys"

[features]
check-passthrough = []
dont-use-deprecated = []

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1"
